apiVersion: v1
kind: Pod
metadata: 
    name: volume-share-xfusion
    labels:
        name: myapp
spec:
    volumes:
      - name: volume-share
        emptyDir: {}
    containers:
      - name: volume-container-xfusion-1
        image: ubuntu:latest
        command: ["/bin/bash", "-c","sleep 10000"]
        volumeMounts:
          - name: volume-share
            mountPath: /tmp/official
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: volume-container-xfusion-2
        image: ubuntu:latest
        command: ["/bin/bash", "-c", "sleep 10000"]
        volumeMounts:
          - name: volume-share
            mountPath: /tmp/games
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"


          